//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_campania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_campania()
        {
            this.tbl_canjes = new HashSet<tbl_canjes>();
            this.tbl_premios = new HashSet<tbl_premios>();
            this.tbl_puntos = new HashSet<tbl_puntos>();
        }
    
        public int idcampania { get; set; }
        public string nombre { get; set; }
        public int idpais { get; set; }
        public int idlocalidad { get; set; }
        public string tipo { get; set; }
        public string own { get; set; }
        public string bannerdesktop { get; set; }
        public string bannermobile { get; set; }
        public string resumen { get; set; }
        public string preguntasf { get; set; }
        public string video { get; set; }
        public string sorteoganadores { get; set; }
        public string sorteofechas { get; set; }
        public string mensaje { get; set; }
        public string terminoscond { get; set; }
        public string politicasuso { get; set; }
        public string politicasprivacidad { get; set; }
        public string politicatratdatos { get; set; }
        public string productos { get; set; }
        public Nullable<System.DateTime> fregistro { get; set; }
        public Nullable<System.DateTime> fupdate { get; set; }
        public Nullable<System.DateTime> fini { get; set; }
        public Nullable<System.DateTime> ffin { get; set; }
        public string estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_canjes> tbl_canjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_premios> tbl_premios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_puntos> tbl_puntos { get; set; }
    }
}
