//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_premios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_premios()
        {
            this.tbl_canjes = new HashSet<tbl_canjes>();
        }
    
        public int idpremios { get; set; }
        public string nombre { get; set; }
        public int idcampania { get; set; }
        public string imagen { get; set; }
        public string detalle { get; set; }
        public Nullable<int> puntaje { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    
        public virtual tbl_campania tbl_campania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_canjes> tbl_canjes { get; set; }
    }
}
