//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_puntos
    {
        public int id { get; set; }
        public int idcampana { get; set; }
        public int idusr { get; set; }
        public int idcodigo { get; set; }
        public string puntos { get; set; }
        public string ownr { get; set; }
        public System.DateTime registro { get; set; }
    
        public virtual tbl_campania tbl_campania { get; set; }
        public virtual tbl_codigos tbl_codigos { get; set; }
        public virtual tbl_participantes tbl_participantes { get; set; }
    }
}
