//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productos
    {
        public int idprod { get; set; }
        public string categoria { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public string detalles { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
    }
}
