//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsersEntities : DbContext
    {
        public UsersEntities()
            : base("name=UsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_campania> tbl_campania { get; set; }
        public virtual DbSet<tbl_canjes> tbl_canjes { get; set; }
        public virtual DbSet<tbl_codigos> tbl_codigos { get; set; }
        public virtual DbSet<tbl_localidad> tbl_localidad { get; set; }
        public virtual DbSet<tbl_paises> tbl_paises { get; set; }
        public virtual DbSet<tbl_participantes> tbl_participantes { get; set; }
        public virtual DbSet<tbl_premios> tbl_premios { get; set; }
        public virtual DbSet<tbl_productos> tbl_productos { get; set; }
        public virtual DbSet<tbl_puntos> tbl_puntos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    
        public virtual int sp_insert_usuario(string usuario, string clave, string nombre, string apellido, ObjectParameter r)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_usuario", usuarioParameter, claveParameter, nombreParameter, apellidoParameter, r);
        }
    
        public virtual ObjectResult<sp_select_usuarios_Result> sp_select_usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_usuarios_Result>("sp_select_usuarios");
        }
    
        public virtual int sp_registro_participantes(string nombre, string apellidos, string dni, string email, Nullable<int> pais, Nullable<int> localidad, string clave, ObjectParameter r)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var paisParameter = pais.HasValue ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(int));
    
            var localidadParameter = localidad.HasValue ?
                new ObjectParameter("localidad", localidad) :
                new ObjectParameter("localidad", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registro_participantes", nombreParameter, apellidosParameter, dniParameter, emailParameter, paisParameter, localidadParameter, claveParameter, r);
        }
    }
}
